// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  DocDocusaurus: ['intro',
                  {type: 'autogenerated', dirName: 'tutorial-basics'}, 
                  {type: 'autogenerated', dirName: 'tutorial-extras'}],

  Cours6eme: [{type: 'autogenerated', dirName: 'cours_6eme'}],
  
  Cours5eme: [{type: 'autogenerated', dirName: 'cours_5eme'}],

  Cours4eme: [{type: 'autogenerated', dirName: 'cours_4eme'}],

  Cours3eme: [{type: 'autogenerated', dirName: 'cours_3eme'}],

  Cours2nde: [{type: 'autogenerated', dirName: 'cours_2nde'}],

  Cours1ere: [{type: 'autogenerated', dirName: 'cours_premiere'}],

  CoursTerminale: [{type: 'autogenerated', dirName: 'cours_terminale'}],

};

export default sidebars;
